In [40]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

import json

import warnings
warnings.filterwarnings("ignore")
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/covid19-in-india/StatewiseTestingDetails.csv
/kaggle/input/covid19-in-india/IndividualDetails.csv
/kaggle/input/covid19-in-india/covid_19_india.csv
/kaggle/input/covid19-in-india/HospitalBedsIndia.csv
/kaggle/input/covid19-in-india/ICMRTestingDetails.csv
/kaggle/input/covid19-in-india/population_india_census2011.csv
/kaggle/input/covid19-in-india/AgeGroupDetails.csv
/kaggle/input/covid19-in-india/ICMRTestingLabs.csv

In [41]:
import pandas as pd
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
import math
import numpy as np
import matplotlib.ticker as ticker
import matplotlib.animation as animation
%matplotlib inline

data= pd.read_csv('../input/covid19-in-india/covid_19_india.csv')
data.head()

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3

In [42]:
ICMRTestingDetailsDS  = pd.read_csv('/kaggle/input/covid19-in-india/ICMRTestingDetails.csv')
ICMRTestingDetailsDS.head()

,SNo,DateTime,TotalSamplesTested,TotalIndividualsTested,TotalPositiveCases,Source
0,1,13/03/20 18:00,6500.0,5900.0,78.0,Press_Release_ICMR_13March2020.pdf
1,2,18/03/20 18:00,13125.0,12235.0,150.0,ICMR_website_update_18March_6PM_IST.pdf
2,3,19/03/20 18:00,14175.0,13285.0,182.0,ICMR_website_update_19March_6PM_IST.pdf
3,4,20/03/20 18:00,15404.0,14514.0,236.0,ICMR_website_update_20March_6PM_IST.pdf
4,5,21/03/20 18:00,16911.0,16021.0,315.0,ICMR_website_update_21March_6PM_IST.pdf

In [43]:
population_india_census2011DS = pd.read_csv('/kaggle/input/covid19-in-india/population_india_census2011.csv')
population_india_census2011DS.head(10)

,Sno,State / Union Territory,Population,Rural population,Urban population,Area,Density,Gender Ratio
0,1,Uttar Pradesh,199812341,155317278,44495063,"240,928 km2 (93,023 sq mi)","828/km2 (2,140/sq mi)",912
1,2,Maharashtra,112374333,61556074,50818259,"307,713 km2 (118,809 sq mi)",365/km2 (950/sq mi),929
2,3,Bihar,104099452,92341436,11758016,"94,163 km2 (36,357 sq mi)","1,102/km2 (2,850/sq mi)",918
3,4,West Bengal,91276115,62183113,29093002,"88,752 km2 (34,267 sq mi)","1,029/km2 (2,670/sq mi)",953
4,5,Madhya Pradesh,72626809,52557404,20069405,"308,245 km2 (119,014 sq mi)",236/km2 (610/sq mi),931
5,6,Tamil Nadu,72147030,37229590,34917440,"130,058 km2 (50,216 sq mi)","555/km2 (1,440/sq mi)",996
6,7,Rajasthan,68548437,51500352,17048085,"342,239 km2 (132,139 sq mi)",201/km2 (520/sq mi),928
7,8,Karnataka,61095297,37469335,23625962,"191,791 km2 (74,051 sq mi)",319/km2 (830/sq mi),973
8,9,Gujarat,60439692,34694609,25745083,"196,024 km2 (75,685 sq mi)",308/km2 (800/sq mi),919
9,10,Andhra Pradesh,49577103,34966693,14610410,"162,968 km2 (62,922 sq mi)",303/km2 (780/sq mi),993

In [44]:
df_Hos  = pd.read_csv('/kaggle/input/covid19-in-india/HospitalBedsIndia.csv')
df_Hos.head()

,Sno,State/UT,NumPrimaryHealthCenters_HMIS,NumCommunityHealthCenters_HMIS,NumSubDistrictHospitals_HMIS,NumDistrictHospitals_HMIS,TotalPublicHealthFacilities_HMIS,NumPublicBeds_HMIS,NumRuralHospitals_NHP18,NumRuralBeds_NHP18,NumUrbanHospitals_NHP18,NumUrbanBeds_NHP18
0,1,Andaman & Nicobar Islands,27,4,NaN,3,34,1246,27,575,3,500
1,2,Andhra Pradesh,1417,198,31.0,20,1666,60799,193,6480,65,16658
2,3,Arunachal Pradesh,122,62,NaN,15,199,2320,208,2136,10,268
3,4,Assam,1007,166,14.0,33,1220,19115,1176,10944,50,6198
4,5,Bihar,2007,63,33.0,43,2146,17796,930,6083,103,5936

In [45]:
df_Hos["Total Number of Beds per state and UT"]= (df_Hos["NumRuralBeds_NHP18"]+df_Hos["NumUrbanBeds_NHP18"])//2
df_Hos.head()
#df_Hos["NumPublicBeds_HMIS"]+

,Sno,State/UT,NumPrimaryHealthCenters_HMIS,NumCommunityHealthCenters_HMIS,NumSubDistrictHospitals_HMIS,NumDistrictHospitals_HMIS,TotalPublicHealthFacilities_HMIS,NumPublicBeds_HMIS,NumRuralHospitals_NHP18,NumRuralBeds_NHP18,NumUrbanHospitals_NHP18,NumUrbanBeds_NHP18,Total Number of Beds per state and UT
0,1,Andaman & Nicobar Islands,27,4,NaN,3,34,1246,27,575,3,500,537
1,2,Andhra Pradesh,1417,198,31.0,20,1666,60799,193,6480,65,16658,11569
2,3,Arunachal Pradesh,122,62,NaN,15,199,2320,208,2136,10,268,1202
3,4,Assam,1007,166,14.0,33,1220,19115,1176,10944,50,6198,8571
4,5,Bihar,2007,63,33.0,43,2146,17796,930,6083,103,5936,6009

In [46]:
df_Bed_Total = df_Hos[["Sno","State/UT","Total Number of Beds per state and UT"]]
df_Bed_Total.head(30)

    Sno                   State/UT  Total Number of Beds per state and UT
0     1  Andaman & Nicobar Islands                                    537
1     2             Andhra Pradesh                                  11569
2     3          Arunachal Pradesh                                   1202
3     4                      Assam                                   8571
4     5                      Bihar                                   6009
5     6                 Chandigarh                                    389
6     7               Chhattisgarh                                   4706
7     8       Dadra & Nagar Haveli                                    294
8     9                Daman & Diu                                    120
9    10                      Delhi                                  12191
10   11                        Goa                                   1506
11   12                    Gujarat                                  16140
12   13                    Haryana                                   5620
13   14           Himachal Pradesh                                   6199
14   15            Jammu & Kashmir                                   5825
15   16                  Jharkhand                                   5392
16   17                  Karnataka                                  35082
17   18                     Kerala                                  19002
18   19                Lakshadweep                                    150
19   20             Madhya Pradesh                                  14419
20   21                Maharashtra                                  25723
21   22                    Manipur                                    713
22   23                  Meghalaya                                   2228
23   24                    Mizoram                                    998
24   25                   Nagaland                                    940
25   26                     Odisha                                   9259
26   27                 Puducherry                                   1784
27   28                     Punjab                                   8966
28   29                  Rajasthan                                  15924
29   30                     Sikkim                                    780

In [47]:
df_Bed_Total["Total Number of Beds per state and UT"].sum() #using half of beds for COvid patients.

710752

In [48]:
import folium
import json

In [56]:
india_map = folium.Map(location=[20.5937, 78.9629], zoom_start=5)

state_geo = os.path.join('/kaggle/input/indian-state-json/states2.json')

folium.Choropleth(
    geo_data=state_geo,
    name='choropleth',
    data=df_Bed_Total,
    columns=['State/UT', 'Total Number of Beds per state and UT'],
    key_on='feature.id',
    fill_color='YlGn',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Total Number of Beds per state and UT'
).add_to(india_map)

folium.LayerControl().add_to(india_map)





## choropleth map for total no. beds in gov. hospital
'''
india_map2 = folium.Map(location=[20.5937, 78.9629], zoom_start=5)

state_geo = os.path.join('../input/indian-state-json/states2.json')

folium.Choropleth(
    geo_data=state_geo,
    name='choropleth',
    data=df_Bed_Total,
    columns=['State/UT', 'Total Number of Beds per state and UT'],
    key_on='feature.id',
    fill_color='OrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='Total Number of Beds per state and UT'
).add_to(india_map)

folium.LayerControl().add_to(india_map) '''
india_map

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/input/indian-state-json/states2.json'